### ISSUE TITLE
Example for rendering LaTeX in pdf using JLaTeXMath

### ISSUE THREAD

**Issue by moritzfl** [Arnauld/gutenberg#2]
Hi,

I am basically trying to render a pdf with a single given LaTeX expression. Optimally with the page only being as large as the space that the expression needs.

I am however struggling to use SourceCodeLaTeXExtension which technically seems to offer that functionality (at least except for the page-size). Could you provide an example for this? - perhaps as a test case ;)

Thank you for reading :)
Moritz

**Comment by moritzfl** [comment]
ok - kind of figured it out now:
```
        Styles styles = new Styles().initDefaults();
        PygmentsAdapter pygmentsAdapter = new PygmentsAdapter(
                new Pygments(),
                new DefaultStyle(), styles);
        SimpleKeyValues kvs = new SimpleKeyValues();
        TeXFormula teXFormula = new TeXFormula(expression);
        TeXIcon teXIcon = teXFormula.createTeXIcon(TeXConstants.STYLE_DISPLAY, 30);

        try {
            ITextContext iTextContext = new ITextContext(kvs, styles).open(file);
            Document document = iTextContext.getDocument();
            document.setPageSize(new com.itextpdf.text.Rectangle(teXIcon.getIconWidth() * 0.5f, teXIcon.getIconHeight() * 0.5f));
            document.setMargins(0, 0, 0, 0);
            document.newPage();
            SourceCodeLaTeXExtension extension = new SourceCodeLaTeXExtension(pygmentsAdapter);
            SourceCode sourceCode = new SourceCode("latex", expression);

            extension.emit(sourceCode, iTextContext);
            iTextContext.getDocument().addHeader("latex", expression);
            iTextContext.close();
        } catch (Exception e) {
            //do meaningful stuff
        }
```

**Comment by Arnauld** [comment]
For your own purpose, you don't even need the gutenberg library, only jlatexmath and itext should be enough.

Almost all the code is in the `SourceCodeLaTeXExtension` and can be copy/paste in your own project.

The idea is to grab the graphics context from the itext document, and then ask jlatexmath to render itself in a java Graphics element.

**Comment by moritzfl** [comment]
Given that I have working code now, I am quite happy - I might however take your advise and look a bit more at itext in conjunction with jlatexmath in the future. I am not very familiar with any pdf framework so I was grateful to find your library that reduced the effort to achieve the desired functionality immensely.
